# 1.create a 3x3 array with random values

In [3]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(2, 2, 2)

print(random_array)

[[[0.15554788 0.36741759]
  [0.74926228 0.51285419]]

 [[0.60644867 0.81823081]
  [0.24409965 0.42492316]]]


# 2.create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
import numpy as np

matrix = np.zeros((5, 5))

np.fill_diagonal(matrix[1:], 2)
np.fill_diagonal(matrix[2:], 3)
np.fill_diagonal(matrix[3:], 4)

print(matrix)

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [3. 2. 0. 0. 0.]
 [4. 3. 2. 0. 0.]
 [0. 4. 3. 2. 0.]]


# 3.create a 8x8 matrix and fill it with a checkboard pattern

In [5]:
import numpy as np


matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1  
matrix[::2, 1::2] = 1  

for row in matrix:
    print(" ".join(map(str, row)))

0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0


# 4.normalize a 5x5 random matrix

In [6]:
import numpy as np

matrix = np.random.rand(5, 5)

min_value = np.min(matrix)
max_value = np.max(matrix)

normalized_matrix = (matrix - min_value) / (max_value - min_value)

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.7520068  0.65438322 0.29633408 0.50476002 0.74347023]
 [0.9421088  0.3528463  0.38772067 0.78386848 0.95716472]
 [0.23596304 0.68257535 0.15121626 0.28822739 0.32184338]
 [0.21145552 0.11663155 0.85446641 0.13372699 0.84931581]
 [0.39658284 0.21610441 0.05829017 0.36179015 0.51524366]]

Normalized Matrix:
[[0.77176134 0.66315489 0.26482439 0.49669873 0.76226439]
 [0.98325026 0.32769437 0.36649219 0.80720754 1.        ]
 [0.19766148 0.6945187  0.10338049 0.25580568 0.29320355]
 [0.17039681 0.06490492 0.8857479  0.08392363 0.88001785]
 [0.37635138 0.17556871 0.         0.33764443 0.50836181]]


# 5.how to find common values between two arrays?

In [7]:
import numpy as np

array1 = np.array([1, 6, 3, 4, 5])
array2 = np.array([1, 4, 5, 2, 7])

common_values = np.intersect1d(array1, array2)

print("Common values between the two arrays:", common_values)

Common values between the two arrays: [1 4 5]


# 6.how to get the dates of yesterday,today,and tommorrow?

In [9]:
import numpy as np
from datetime import datetime, timedelta

today = datetime.now()

yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

dates = np.array([yesterday, today, tomorrow])

for date in dates:
    print(date.strftime("%Y-%m-%d"))

2023-09-20
2023-09-21
2023-09-22


# 7.consider two random array A and B,check if they are equal

In [15]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(4, 5)
B = np.random.rand(4, 5)

# Check if A and B are equal
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8.create random vector of size 10 and replace the maximum value by 0

In [17]:
import numpy as np

random_vector = np.random.rand(10)

max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print("Random vector with the maximum value replaced:", random_vector)



Random vector with the maximum value replaced: [0.23074234 0.7649117  0.         0.74999925 0.33940382 0.48954894
 0.33898512 0.17949026 0.1709866  0.46345098]


# 9.how to print all the values of an array?

In [16]:
import numpy as np

my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for value in np.nditer(my_array):
    print(value)

1
2
3
4
5
6
7
8
9


# 10.subtract the mean of each row of a matrix

In [18]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [2, 8, 1]])

row_means = np.mean(matrix, axis=1)

result_matrix = matrix - row_means.reshape(-1, 1)

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(result_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [2 8 1]]

Matrix with Row Means Subtracted:
[[-1.          0.          1.        ]
 [-1.          0.          1.        ]
 [-1.66666667  4.33333333 -2.66666667]]


# 11.consider a given vector,how to add 1 to each element indexed by a second vector (be careful with repeated indices)

In [19]:
import numpy as np

given_vector = np.array([1, 2, 3, 4, 5])

indices_vector = np.array([1, 3, 2, 1, 4, 0])

index_counts = {}
for index in indices_vector:
    if index in index_counts:
        index_counts[index] += 1
    else:
        index_counts[index] = 1

result_vector = given_vector.copy()
for index, count in index_counts.items():
    result_vector[index] += count

print(result_vector)

[2 4 4 5 6]


# 12.how to get the diagonal if a dot product

In [26]:
import numpy as np

matrix_A = np.array([[1, 2],
                     [3, 4]])

matrix_B = np.array([[5, 6],
                     [7, 8]])

dot_product = np.dot(matrix_A, matrix_B)

diagonal = np.diagonal(dot_product)

print("Dot Product:")
print(dot_product)

print("Diagonal of the Dot Product:")
print(diagonal)

Dot Product:
[[19 22]
 [43 50]]
Diagonal of the Dot Product:
[19 50]


# 13.how to find the most frequent value in an array?

In [27]:
import numpy as np

my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

counts = np.bincount(my_array)

most_frequent_value = np.argmax(counts)

print("Array:", my_array)
print("Most frequent value:", most_frequent_value)

Array: [1 2 2 3 3 3 4 4 4 4]
Most frequent value: 4


# 14.how to get the n largest values of an array

In [23]:
import numpy as np

arr = np.array([172, 8945, 6523, 876, 788, 99, 30, 55, 786, 109])

n = 4

largest_values = np.partition(arr, -n)[-n:]

print("Array:", arr)
print(f"The {n} largest values are:", largest_values)

Array: [ 172 8945 6523  876  788   99   30   55  786  109]
The 4 largest values are: [ 788  876 6523 8945]


# 15.how to create a record array from a regular array?

In [37]:
import numpy as np

# Create a regular array with data
data = [(1, 'raj', 29),
        (2, 'parimala', 23),
        (3, 'jaya', 42)]

# Define data types and field names for the record array
dtypes = [('id', int), ('name', 'U10'), ('age', int)]

# Create the record array
record_array = np.array(data, dtype=dtypes)

# Access elements by field name
print(record_array['id'])   # Access the 'id' field
print(record_array['name']) # Access the 'name' field
print(record_array['age'])  # Access the 'age' field

[1 2 3]
['raj' 'parimala' 'jaya']
[29 23 42]


# 16.how to swap two rows of an array?

In [25]:
import numpy as np

array = np.array([[1, 2, 3],
                  [3, 4, 5],
                  [7, 8, 9]])

row1 = 0  # Row 1 (0-based index)
row2 = 2  # Row 2 (0-based index)

array[row1], array[row2] = array[row2].copy(), array[row1].copy()

print(array)

[[7 8 9]
 [3 4 5]
 [1 2 3]]


# 17.write python code to reshape to the next dimension of numpy array?

In [36]:
import numpy as np

# Create a sample NumPy array
original_array = np.array([1, 2, 3, 4, 5, 6])  # 1-D array with 6 elements

# Determine the new shape by increasing the dimension by 1
new_shape = (original_array.size, 1)

# Reshape the array to the next dimension
reshaped_array = original_array.reshape(new_shape)

# Print the original and reshaped arrays
print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
